name: Build and Publish lqweb to GHCR

on:
  push:
    tags:
      - '*'  # Runs on all tags

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/lqweb

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract tag and build args
        id: vars
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "RELEASE_URL=https://github.com/lavenderdotpet/LibreQuake/releases/download/$TAG/full.zip" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            --build-arg RELEASE_URL=$RELEASE_URL \
            -t $IMAGE_NAME:$TAG \
            -t $IMAGE_NAME:latest \
            .

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:$TAG
          docker push $IMAGE_NAME:latest
